module OpenBreweryDb
  # Sends an HTTP request to Open Brewery DB at the specified endpoint.
  class Request
    attr_reader endpoint: String
    attr_reader per_page: Integer
    attr_reader timeout: Integer

    def initialize: (String endpoint, Hash[String, Integer] | nil options) -> void
  end
end
